import { jsPDF } from 'jspdf';

/**
 * generateAffidavitPDF
 * Creates a formatted PDF for an affidavit and triggers browser download.
 */
export function generateAffidavitPDF(affidavit) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentW = pageW - margin * 2;
  let y = 20;

  const addLine = (text, opts = {}) => {
    const { size = 11, bold = false, center = false, color = [30, 40, 60] } = opts;
    doc.setFontSize(size);
    doc.setFont('times', bold ? 'bold' : 'normal');
    doc.setTextColor(...color);
    const x = center ? pageW / 2 : margin;
    const align = center ? 'center' : 'left';
    const lines = doc.splitTextToSize(text, contentW);
    doc.text(lines, x, y, { align });
    y += lines.length * (size * 0.45) + 3;
  };

  const addSpace = (n = 6) => { y += n; };
  const addHR = () => {
    doc.setDrawColor(200, 190, 170);
    doc.line(margin, y, pageW - margin, y);
    y += 5;
  };

  // Header
  addLine('GOVERNMENT OF INDIA', { size: 10, center: true, color: [100, 100, 100] });
  addSpace(2);
  addLine('AFFIDAVIT', { size: 18, bold: true, center: true, color: [11, 31, 58] });
  addSpace(2);
  addLine(`[ ${affidavit.template || 'General'} ]`, { size: 11, center: true, color: [150, 120, 60] });
  addHR();

  // Body content
  const lines = (affidavit.content || '').split('\n');
  lines.forEach((line) => {
    if (line.trim() === '') { addSpace(3); return; }
    if (line.match(/^\d+\./)) {
      addLine(line, { size: 11, bold: false });
    } else if (line.toUpperCase() === line && line.length > 5) {
      addLine(line, { size: 12, bold: true });
    } else {
      addLine(line, { size: 11 });
    }
  });

  addSpace(10);
  addHR();

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text('Document ID: ' + (affidavit.affidavitId || 'DRAFT'), margin, y);
  doc.text('Generated via JustEase — www.justease.in', pageW - margin, y, { align: 'right' });
  y += 5;
  doc.text('⚠️  This document requires attestation by a Notary/First Class Magistrate for official use.', margin, y);

  doc.save(`${affidavit.affidavitId || 'affidavit'}.pdf`);
}

/**
 * generateCaseSummaryPDF
 * Creates a case summary PDF.
 */
export function generateCaseSummaryPDF(caseData) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 20;
  let y = 20;

  doc.setFontSize(18);
  doc.setFont('times', 'bold');
  doc.setTextColor(11, 31, 58);
  doc.text('CASE SUMMARY', pageW / 2, y, { align: 'center' });
  y += 10;

  doc.setDrawColor(200, 190, 170);
  doc.line(margin, y, pageW - margin, y);
  y += 8;

  const row = (label, value) => {
    doc.setFontSize(10);
    doc.setFont('times', 'bold');
    doc.setTextColor(80, 100, 130);
    doc.text(label + ':', margin, y);
    doc.setFont('times', 'normal');
    doc.setTextColor(30, 40, 60);
    const val = doc.splitTextToSize(String(value || '—'), pageW - margin - 70);
    doc.text(val, margin + 50, y);
    y += val.length * 6 + 2;
  };

  row('Case ID', caseData.caseId);
  row('Title', caseData.title);
  row('Category', caseData.category);
  row('Status', caseData.status);
  row('Filed By', caseData.filerName);
  row('Assigned Judge', caseData.assignedJudgeName || 'Unassigned');
  row('Filed On', new Date(caseData.createdAt).toLocaleDateString('en-IN'));
  row('Next Hearing', caseData.nextHearing ? new Date(caseData.nextHearing).toLocaleDateString('en-IN') : 'Not Scheduled');
  row('Relief Sought', caseData.reliefSought);

  y += 6;
  doc.line(margin, y, pageW - margin, y);
  y += 6;

  doc.setFontSize(10);
  doc.setFont('times', 'bold');
  doc.setTextColor(80, 100, 130);
  doc.text('Description:', margin, y);
  y += 6;
  doc.setFont('times', 'normal');
  doc.setTextColor(30, 40, 60);
  const desc = doc.splitTextToSize(caseData.description || '', pageW - margin * 2);
  doc.text(desc, margin, y);
  y += desc.length * 6 + 10;

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by JustEase — Legal Assistance Platform  |  ⚠️ Not an official court document.', pageW / 2, y, { align: 'center' });

  doc.save(`${caseData.caseId}-summary.pdf`);
}
